### ISSUE TITLE
Managing the upstreaming of libgccjit patches

### ISSUE THREAD

**Issue by davidmalcolm** [antoyo/rustc_codegen_gcc#8]
Readme.md  currently states that two libgccjit patches are needed, but judging by the patches you've been sending me for review I'm guessing that that's currently out of date.

Idea: have a "gcc-patches" subdirectory, containing the patches to libgccjit currently needed to build the project.  Ideally the subdirectory will eventually become empty as all the support is merged into the gcc source tree, but it at least documents exactly what you're building against (and the readme probably should document exactly which revision of the gcc tree you're patching).  It may help with CI, and also gives me a good at-a-glance way of seeing if I have anything of yours I need to review.

**Comment by antoyo** [comment]
Yup, I wanted to send all the patches I had before updating it (I just sent you the last one).

Sure, I will add the patches in a subdirectory in the following days.

CI won't pass anything soon since I have many bugs to fix and features to implement.

Were you asking because you tried running this?

**Comment by antoyo** [comment]
Also, I'm not sure if it would against gcc policies, but I could open PRs here for those patches to do the reviews with an easier tool than email so that it's easier to keep tracks of what issues remain and those that are resolved (I'm having a hard time figuring that out, especially with my big patch that adds the reflection API).

When all issues are solved, we could then post the patch to the gcc mailing list for a final review by other people.

What do you think?

**Comment by davidmalcolm** [comment]
> Yup, I wanted to send all the patches I had before updating it (I just sent you the last one).
> 
> ~Sure, I will add the patches in a subdirectory in the following days.~
> **Edit:** The patches were added: they will obviously conflict with one another, but should be easy to fix.

Thanks.  I see that all of them are of the form "0001-*.patch" so it's not clear what order they go in.  I was more thinking a `git format-patch master `so that it emits all of the patches in numbered order in a form that "git am" can apply.

But it might make more sense to instead have the readme point people at a fork of https://github.com/gcc-mirror/gcc with a branch holding the patches that are needed, so that it's trivial to see what patches still need to be merged into gcc upstream.  That would probably be easier for you and other people to work with.

Are you also using a forked copy of the libgccjit rust bindings?  If so, maybe that should be published too, and linked to from the readme.

> 
> CI won't pass anything soon since I have many bugs to fix and features to implement.
> 
> Were you asking because you tried running this?

I did try (and failed) a few months ago.  My question was more about making it easy to see what patches I need to review.  You seem to be doing a great job of finding bugs and features that libgccjit doesn't implement yet, so I expect that there will be a few more patches along the way.

Hope this is constructive

**Comment by antoyo** [comment]
> Are you also using a forked copy of the libgccjit rust bindings? If so, maybe that should be published too, and linked to from the readme.

Yes, this is in the `Cargo.toml` file.

I added my fork of gcc in the readme.

**Comment by antoyo** [comment]
By the way, I renamed the files so that they have different number prefixes: even though they cannot be applied on gcc master branch without conflicting, that will at least tell you the order in which they should be merged (which is important because they add different ABI numbers).

**Comment by antoyo** [comment]
As requested for the inclusion into rustc, the patches were moved out of this repository and are now [in this one](https://github.com/antoyo/libgccjit-patches).

**Comment by eternal-sorrow** [comment]
So? What's the status here? Were the patches upsteamed? Is it possible to build it with the upstream libgccjit? If not, why the issue is closed?

**Comment by antoyo** [comment]
This issue was opened by the maintainer of libgccjit in order to find a way to have a list of patches that were sent for review and that way was found, so that's why the issue is closed.

The patches weren't merged upstream yet.
`rustc_codegen_gcc` has a feature `master` that you can disable which will allow you to build this project with libgccjit 12, but with a few missing features.

**Comment by eternal-sorrow** [comment]
Is there any way to track the progress of the patches being merged upstream? Some mailing list thread maybe?

**Comment by antoyo** [comment]
This [page](https://patchwork.sourceware.org/project/gcc/list/?submitter=35566) will list most of them (I believe there's one or 2 missing, not sure why).

**Comment by eternal-sorrow** [comment]
Thanks.
